context:
  version: "0.13.5"

package:
  name: tifffile
  version: "{{ version }}"

source:
  git_url: https://github.com/blink1073/tifffile
  git_tag: "v{{ version }}"

build:
  number: 3
  # conda 4.4+
  skip: 
    - blas_impl != "mkl" and win
  requires_features:
    blas: "{{ blas_impl }}"
  # conda 4.3-
  features:
    - sel(x86 and blas_impl != "mkl"): nomkl

  script: python setup.py install

requirements:
  build:
    - sel(blas_impl != "mkl"): nomkl
    - python
    - numpy
    - setuptools

  run:
    - sel(blas_impl != "mkl"): nomkl
    - python
    - '{{ pin_compatible("numpy", min_pin="x.x", max_pin="x.x") }}'

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license:  BSD License
  summary: 'Read and write image data from and to TIFF files.'
