# Generated by vinca http://github.com/seanyen/vinca.
# DO NOT EDIT!
# if [ -z "${CONDA_PREFIX}" ]; then
#	exit 0;
# fi

# Don't do anything when we are in conda build.
# if [ ! -z "${SYS_PREFIX}" ]; then
# 	exit 0;
# fi

# Not sure if this is necessary on UNIX?
# export QT_PLUGIN_PATH=$CONDA_PREFIX\plugins

source $CONDA_PREFIX/setup.sh

# Looks unnecessary for UNIX
# unset PYTHONHOME=