# generated by datamodel-codegen:
#   filename:  about.json
#   timestamp: 2021-11-25T18:26:02+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Model(BaseModel):
    channels: List[str]
    conda_build_version: str
    conda_private: bool
    conda_version: str
    description: str
    dev_url: str
    doc_url: str
    env_vars: dict
    extra: dict
    home: str
    identifiers: List[str]
    keywords: List[str]
    license_: str = Field(alias="license")
    license_family: str
    license_file: str
    root_pkgs: List[str]
    summary: str
    tags: List[str]


if __name__ == "__main__":
    print(Model.schema_json(indent=2))
