# generated by datamodel-codegen:
#   filename:  about.json
#   timestamp: 2021-11-25T18:26:02+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class EnvVars(BaseModel):
    CIO_TEST: str


class Extra(BaseModel):
    copy_test_source_files: bool
    final: bool
    recipe_maintainers: List[str] = Field(..., alias="recipe-maintainers")


class Model(BaseModel):
    channels: List[str]
    conda_build_version: str
    conda_private: bool
    conda_version: str
    description: str
    dev_url: str
    doc_url: str
    env_vars: EnvVars
    extra: Extra
    home: str
    identifiers: List
    keywords: List
    license_: str = Field(alias="license")
    license_family: str
    license_file: str
    root_pkgs: List[str]
    summary: str
    tags: List
