# generated by datamodel-codegen:
#   filename:  index.json
#   timestamp: 2021-11-25T18:29:15+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Model(BaseModel):
    arch: str
    build: str
    build_number: int
    constrains: List[str]
    depends: List[str]
    license_: str = Field(alias="license")
    license_family: str
    name: str
    platform: str
    subdir: str
    timestamp: int
    version: str


if __name__ == "__main__":
    print(Model.schema_json(indent=2))
