context:
  name: 'scikit-geometry'
  version: '0.1.2'

recipe_version: 1.1

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/scikit-geometry/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 11d2ca3361b680b27e21ce651cf9f3a9dc017195626c73627cc1d6ee6b745ff4

build:
  number: 3
  skip:
    - py<35

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
  host:
    - pip
    - python
    - pybind11
    - cgal-cpp 5.0
  run:
    - python
    - cgal-cpp 5.0
    - matplotlib-base
    # Just to silence the warnings, but not adding vs2015_runtime for win...
    - boost-cpp
    - sel(win): mpir
    - sel(not win): gmp
    - mpfr

test:
  imports:
    - skgeom
    - skgeom.draw

about:
  home: https://github.com/scikit-geometry/scikit-geometry
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: Scientific Python Geometric Algorithms Library
  doc_url: https://scikit-geometry.github.io/scikit-geometry
  dev_url: https://github.com/scikit-geometry/scikit-geometry

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay