name: Linters (Python)

on:
  push:
   branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/lint.yml
    - name: Run all linters
      shell: bash -l {0}
      run: |
        pre-commit run --all-files --verbose
