name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: install mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: tests/env.yml
    - name: Install boa
      shell: bash -l {0}
      run: |
        pip install .
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda config --add channels conda-forge
        conda config --set channel_priority strict
        pytest tests
      env:
        PYTHONUTF8: 1
